# $Id: Makefile,v 1.1 2002/04/01 07:33:59 ehood Exp $

.PHONY: default

TOP     = ../..
SUBDIRS = \
	  CharEnt \
	  # End SUBDIRS

include $(TOP)/etc/variables.mk


default: make_subdirs perl_syntax


include $(TOP)/etc/rules.mk
